# Generated by Django 4.1.3 on 2022-11-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0003_customuser_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
